### ISSUE TITLE
HART 5 -- Universal Command (LongAddressing)

### ISSUE THREAD

**Issue by JohnShamu** [biplabro/HART-Protocol-Basics#1]
Hello @biplabro,

May you kindly assist:
I have been trying to carry out further communication with a Slave Device (FUJI A2 V5) on Windows 10.
Command 0 In short addressing mode works fine:
 I send `FFFFFFFFFFFFFFFFFFFF0280000082`  and receive -- 
`"FF"	"FF"	"FF"	"FF"	"FF"	"06"	"80"	"00"	"0E"	"00"	"00"	"FE"	"15"	"02"	"05"	"05"	"03"	"0F"	"10"	"00"	"0D"	"91"	"43"	"A2"`

I then use the long address `["15"	"02" "0D"	"91"	"43"]` from Command Zero to get the Primary Variable (PV) using Command 1 as follows:

I send `FFFFFFFFFF8295020D91430001CB` but then I don't receive anything at all...

Am I missing something?

Thanks for the help.
/John

**Comment by biplabro** [comment]
Hi @JohnShamu

It's a great pleasure to hear from you. 
can you please try & confirm with the following bytecode "FFFFFFFFFFFFFFFFFFFF0280**01**00**83**" as command 1 request to slave

Breakdown: 
FFFFFFFFFFFFFFFFFFFF0280 (preamble & initial bytes)
**01** (Command code)
00 (data in command)
**83** (checksum)

Command 1 is exactly the same as command 0 (the string you have mentioned) except the command code & checksum, these two bytes will be different in command 1. 

Commands Reference:[ https://github.com/biplabro/HART-Protocol-Fundamentals/blob/main/04.%20Resources/HART_commands.pdf ]( https://github.com/biplabro/HART-Protocol-Fundamentals/blob/main/04.%20Resources/HART_commands.pdf )

Looking forward to your response. 
Regards.
Roy.

**Comment by biplabro** [comment]
For more info on Long address reference, please refer to this document. Page 22, **Telegram** structure

[https://github.com/biplabro/HART-Protocol-Fundamentals/blob/main/04.%20Resources/Samson%20HART%20Communications.pdf](https://github.com/biplabro/HART-Protocol-Fundamentals/blob/main/04.%20Resources/Samson%20HART%20Communications.pdf)

**Comment by JohnShamu** [comment]
Hello Roy (@biplabro),

Thanks to you, I managed to solve the problem, it was a nasty logical error. I had swapped the command '01' (Command code)
'00' (data in command)… So for Command '00' the code works since the data is also '00'.

Anyway I am now working on Command 34 '(hex 22)': Setting the Damping value of a Pressure Sensor. When I send only '00' in the data Bytes the Device responds CORRECTLY with a Command Response Code of 5 -- _Too few data Bytes_.
This is because the Command 34 requires 4 bytes, i.e.  Bytes '0 - 3' of the command are to be sent as IEEE754 float. So let's
[FCX-AIII-AIIV5_HART_Command-Set_EndUser (1).pdf](https://github.com/biplabro/HART-Protocol-Fundamentals/files/8420201/FCX-AIII-AIIV5_HART_Command-Set_EndUser.1.pdf)
 say I want to set the Damping value to 1 sec --I should then send Hex IEEE 754 as :  '3F800000' ?

However, if I do this by sending: 'FFFFFFFFFF 82 9A8921633F 22 **3F800000** 71' I don't get any response from the device.
I have also attached the Command Summary of the Device I am using.
Thanks again.

Regards
John

**Comment by biplabro** [comment]
![Frame Delimiter Explanation](https://raw.githubusercontent.com/biplabro/HART-Protocol-Fundamentals/ea786f77cc596ed5df4ddeb8992e8023ac58f2f0/02.%20Images/long_short_addressing_mode.png)

Frame Delimiter. Values ending with 1 inicate burst mode, when the filed device continuously sends sensor informations to the master. Values ending with 2 indicate normal requests, while values ending with 6 indicate responses. There is also a difference between addressing modes signified here: if the byte starts with 0, it indicates long addressing, while 8 means short. As you can see we are now making a request in short addressing mode.

Source: https://kovleventer.com/blog/hart_intro/
